reviews:
  profile: assertive

  # 文件过滤（新版用 path_filters）
  path_filters:
    - "**/*.py"
    - "!venv/**/*"

  # 自定义业务规则（新版必须用 path_instructions）
  path_instructions:
    - path: "**/*.py"
      instructions: |
        1. 所有SQL查询必须使用参数化查询，禁止字符串拼接。
           正确示例：cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))

        2. 禁止使用print语句，必须使用logging模块。
           正确示例：logging.info('订单创建成功：%s', order_id)

        3. 订单金额（order_amount/amount）必须校验非空且>0。
           未校验必须抛出ValueError，错误信息必须包含：订单金额必须为正数
