# .sourcery.yaml 最终可生效版本
rules:
  # 启用内置安全规则（修正错误ID）
  enable:
    - sql-injection-via-concat
    - ensure-file-closed  # 正确的资源泄漏规则ID
  disable: []
  # 加载自定义AST规则（禁止print）
  custom:
    - .sourcery/rules/

reviews:
  instructions:
    # 仅作为备注，辅助审查者理解规则（非执行逻辑）
    - content: "所有数据库查询必须使用参数化查询，禁止字符串拼接构造SQL"
      severity: "CRITICAL"
      paths: ["**/*.py"]
  filter_severity: ["CRITICAL", "WARNING"]
